# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'CaeMlAi'
tagline:          'A Space for Cae + Ml + Ai'
description:      'Let''s dive into the world of CMA!'
url:              'https://caeml.ai'
baseurl:          null
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
    name:        CamelCMA
    url:         'https://caeml.ai'
    email:       camel@caeml.ai

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-admin
  - jekyll-seo-tag
  - jekyll-sitemap

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

github:          'https://github.com/CamelCMA'

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

future: true
